"""remove duplicate time column from events

Revision ID: 495bb19fa25d
Revises: fcd85db49628
Create Date: 2026-06-12 17:50:52.222929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495bb19fa25d'
down_revision = 'fcd85db49628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
