"""add rounds and scores to event

Revision ID: 4ae4f5272f7d
Revises: 495bb19fa25d
Create Date: 2026-06-17 23:34:11.695194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae4f5272f7d'
down_revision = '495bb19fa25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rounds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scores', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('scores')
        batch_op.drop_column('rounds')

    # ### end Alembic commands ###
