"""Новые поля для таблицы Event

Revision ID: f865a8414c99
Revises: f5f3acc6d7aa
Create Date: 2026-05-28 22:06:01.462874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f865a8414c99'
down_revision = 'f5f3acc6d7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('seats', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('seats')
        batch_op.drop_column('location')
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
