"""add team_members, relationships, player_count

Revision ID: fcd85db49628
Revises: c6b9c5741f34
Create Date: 2026-06-12 17:09:39.404749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd85db49628'
down_revision = 'c6b9c5741f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_count', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('player_count')

    op.drop_table('team_members')
    # ### end Alembic commands ###
